name: Commits

on:
  pull_request:
    branches: ["master"]
    types: [opened, reopened, edited, synchronize]
  push:
    branches: ["master"]

jobs:
  use_share:
    steps:
      - name: hey
        uses: ./.github/workflows/shared.yml
